name: CarND
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36h0f667ec_1
  - cryptography=2.6.1=py36h72c5cf5_0
  - idna=2.6=py36h82fb2a8_1
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=hf484d3e_0
  - openssl=1.1.1b=h14c3975_1
  - pycosat=0.6.3=py36h0a5515d_0
  - pycparser=2.18=py36hf9f622e_1
  - pyopenssl=18.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - python=3.6.7=h381d211_1004
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py36he2e5f8d_1
  - ruamel_yaml=0.15.37=py36h14c3975_2
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36h372c433_1
  - sqlite=3.26.0=h67949de_1001
  - tk=8.6.9=h84994c4_1001
  - urllib3=1.22=py36hbe7ace6_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - absl-py==0.5.0
    - astor==0.7.1
    - bleach==1.5.0
    - catkin-pkg==0.4.10
    - docutils==0.14
    - filelock==3.0.10
    - gast==0.2.0
    - gdown==3.8.1
    - grpcio==1.15.0
    - h5py==2.8.0
    - html5lib==0.9999999
    - keras==2.2.4
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - markdown==3.0.1
    - numpy==1.15.2
    - pillow==5.3.0
    - pip==18.1
    - protobuf==3.6.1
    - psutil==5.4.8
    - pyautogui==0.9.38
    - pymouse==1.0
    - pymsgbox==1.0.6
    - pyparsing==2.3.1
    - pyscreeze==0.1.18
    - python-dateutil==2.8.0
    - python3-xlib==0.15
    - pytweening==1.0.3
    - pyyaml==3.13
    - scipy==1.1.0
    - tensorboard==1.6.0
    - tensorflow-gpu==1.6.0
    - termcolor==1.1.0
    - tqdm==4.31.1
    - werkzeug==0.14.1
prefix: your_path_to/anaconda3/envs/CarND

